[package]
name = "guard4api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
futures = { version = "0.3.21", features = ["thread-pool"]}
tokio-util = { version = "0.7.3", features = ["full"] }
tokio-stream = "0.1.9"